# docker-compose.yaml
version: '3'

services:
  ssr-app:
    # Этим ключом мы скажем docker-compose, чтобы он собирал Dockerfile, который
    # находится в папке рядом с docker-compose.yaml
    build:
      context: .
    # Проброс порта так же, как в командной строке — на какой порт хоста какой порт контейнера
    ports:
      - '5000:9001'

  game-server-app:
    # Этим ключом мы скажем docker-compose, чтобы он собирал Dockerfile, который
    # находится в папке рядом с docker-compose.yaml
    build:
      context: ./server
      # Проброс порта так же, как в командной строке — на какой порт хоста какой порт контейнера
    ports:
      - '8081:8081'
