export const CHANGE_USER_GAME_ROLE = 'userData/CHANGE_USER_GAME_ROLE';

export const GET_USER_DATA_START = 'userData/GET_USER_DATA_START';
export const GET_USER_DATA_SUCCESS = 'userData/GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'userData/GET_USER_DATA_FAILURE';

export const CHANGE_USER_AVATAR_START = 'userAvatar/CHANGE_USER_AVATAR_START';
export const CHANGE_USER_AVATAR_SUCCESS =
  'userAvatar/CHANGE_USER_AVATAR_SUCCESS';
export const CHANGE_USER_AVATAR_FAILURE =
  'userAvatar/CHANGE_USER_AVATAR_FAILURE';

export const CHANGE_USER_DATA_START = 'changeUserData/CHANGE_USER_DATA_START';
export const CHANGE_USER_DATA_SUCCESS =
  'changeUserData/CHANGE_USER_DATA_SUCCESS';
export const CHANGE_USER_DATA_FAILURE =
  'changeUserData/CHANGE_USER_DATA_FAILURE';

export const CHANGE_IS_LOGGED_IN_STATUS = 'user/CHANGE_IS_LOGGED_IN_STATUS';
