name: Croco-CI-test
env:
  DB_USER: 'postgres'
  DB_HOST: 'postgres'
  DB_NAME: 'croco-db'
  DB_PASSWORD: 'newPassword'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'newPassword'
  POSTGRES_DB: 'croco-db'
  PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
  PGADMIN_DEFAULT_PASSWORD: 'secret'
  PGADMIN_LISTEN_PORT: '80'
  DEPLOY_PATH: /var/www/croco-test1
  BUILD_SCRIPT_OUTPUT: .
on:
  push:
    branches:
      - main
      - S9T64
  pull_request:
    branches:
      - S9T64
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Copy from repository
        uses: actions/checkout@v2 #копируем все из репозитория
      - name: Run docker-compose stack
        run: docker-compose up -d --build
      - name: Check folder
        run: pwd
      - name: Check files
        run: ls -ltr
      ### Доставляем исходники приложения на сервер
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          source: ${{ env.BUILD_SCRIPT_OUTPUT }}
          target: ${{ env.DEPLOY_PATH }}
          strip_components: 1

      - name: Execute ssh command via using private key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_SERVER_KEY }}
          script: |
            bash /var/www/croco-test1/run-bash.sh
